// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: blahblah

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern lv_obj_t * ui_Label2;
extern void ui_event_transitionTime(lv_event_t * e);
extern lv_obj_t * ui_transitionTime;
extern lv_obj_t * ui_Label3;
extern void ui_event_Red(lv_event_t * e);
extern lv_obj_t * ui_Red;
extern lv_obj_t * ui_Label4;
extern void ui_event_Green(lv_event_t * e);
extern lv_obj_t * ui_Green;
extern lv_obj_t * ui_Label5;
extern void ui_event_Blue(lv_event_t * e);
extern lv_obj_t * ui_Blue;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

