// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: blahblah

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Colorwheel2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_transitionTime = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Red = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Green = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Blue = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetBackgroundButtonFunction(e);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        sliderBrightnessFunction(e);
    }
}

void ui_event_Colorwheel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        colorWheelFunction(e);
    }
}

void ui_event_transitionTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        sliderTimeFunction(e);
    }
}

void ui_event_Red(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeColorRed(e);
    }
}

void ui_event_Green(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeColorGreen(e);
    }
}

void ui_event_Blue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeColorBlue(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 64);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -3);
    lv_obj_set_y(ui_Button1, 51);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 1, 100);
    lv_slider_set_value(ui_Slider1, 25, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -79);
    lv_obj_set_y(ui_Slider1, 105);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -3);
    lv_obj_set_y(ui_Label1, 52);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Clear \nscreen");

    ui_Colorwheel2 = lv_colorwheel_create(ui_Screen1, true);
    lv_obj_set_width(ui_Colorwheel2, 100);
    lv_obj_set_height(ui_Colorwheel2, 100);
    lv_obj_set_x(ui_Colorwheel2, 96);
    lv_obj_set_y(ui_Colorwheel2, 57);
    lv_obj_set_align(ui_Colorwheel2, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -115);
    lv_obj_set_y(ui_Label2, 83);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Brightness");

    ui_transitionTime = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_transitionTime, 0, 30);
    lv_slider_set_value(ui_transitionTime, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_transitionTime) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_transitionTime, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_transitionTime, 76);
    lv_obj_set_height(ui_transitionTime, 10);
    lv_obj_set_x(ui_transitionTime, -109);
    lv_obj_set_y(ui_transitionTime, 49);
    lv_obj_set_align(ui_transitionTime, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -99);
    lv_obj_set_y(ui_Label3, 24);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Transition time");

    ui_Red = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Red, 39);
    lv_obj_set_height(ui_Red, 38);
    lv_obj_set_x(ui_Red, -134);
    lv_obj_set_y(ui_Red, -93);
    lv_obj_set_align(ui_Red, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Red, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Red, lv_color_hex(0xFF3131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Red, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Red);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Red");

    ui_Green = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Green, 49);
    lv_obj_set_height(ui_Green, 38);
    lv_obj_set_x(ui_Green, -85);
    lv_obj_set_y(ui_Green, -93);
    lv_obj_set_align(ui_Green, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Green, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Green, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Green, lv_color_hex(0x31FF6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Green, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Green);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Green");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1C1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blue = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Blue, 49);
    lv_obj_set_height(ui_Blue, 38);
    lv_obj_set_x(ui_Blue, -28);
    lv_obj_set_y(ui_Blue, -93);
    lv_obj_set_align(ui_Blue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Blue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Blue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blue, lv_color_hex(0x313BFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Blue);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Blue");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorwheel2, ui_event_Colorwheel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_transitionTime, ui_event_transitionTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Red, ui_event_Red, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Green, ui_event_Green, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Blue, ui_event_Blue, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Slider1 = NULL;
    ui_Label1 = NULL;
    ui_Colorwheel2 = NULL;
    ui_Label2 = NULL;
    ui_transitionTime = NULL;
    ui_Label3 = NULL;
    ui_Red = NULL;
    ui_Label4 = NULL;
    ui_Green = NULL;
    ui_Label5 = NULL;
    ui_Blue = NULL;
    ui_Label6 = NULL;

}
