// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: blahblah

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ballsFunction(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
