// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ballsFunction(lv_event_t * e)
{
	// Your code here
}

void sliderBrightnessFunction(lv_event_t * e)
{
	// Your code here
}

void colorWheelFunction(lv_event_t * e)
{
	// Your code here
}

void resetBackgroundButtonFunction(lv_event_t * e)
{
	// Your code here
}

void changeColorRed(lv_event_t * e)
{
	// Your code here
}

void changeColorGreen(lv_event_t * e)
{
	// Your code here
}

void changeColorBlue(lv_event_t * e)
{
	// Your code here
}

void sliderTimeFunction(lv_event_t * e)
{
	// Your code here
}

void colorWheelReleaseFunction(lv_event_t * e)
{
	// Your code here
}
