// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: blahblah

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void resetBackgroundButtonFunction(lv_event_t * e);
void sliderBrightnessFunction(lv_event_t * e);
void colorWheelFunction(lv_event_t * e);
void sliderTimeFunction(lv_event_t * e);
void changeColorRed(lv_event_t * e);
void changeColorGreen(lv_event_t * e);
void changeColorBlue(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
